### ISSUE TITLE
运行失败

### ISSUE THREAD

**Issue by lihaoyee** [songkuixi/TouchBreakout#1]
Code Signing Error: No account for team "VEBQ28K9EA". Add a new account in the Accounts preference pane or verify that your accounts have valid credentials.
Code Signing Error: No signing certificate "Mac Development" found:  No "Mac Development" signing certificate matching team ID "VEBQ28K9EA" with a private key was found.
请问这两个问题怎么解决🙏🙏

**Comment by songkuixi** [comment]
因为我开发时候是用自己的开发者证书签名运行的，在你的电脑上运行时要在 Target -> General -> Signing 里面改成自己的开发者证书。

**Comment by krayc425** [comment]
@lihaoyee 因为我开发时候是用自己的开发者证书签名运行的，在你的电脑上运行时要在 Target -> General -> Signing 里面改成自己的开发者证书。

**Comment by lihaoyee** [comment]
谢谢~
