### ISSUE TITLE
该哭了

### ISSUE THREAD

**Issue by fandongtongxue** [songkuixi/TouchBreakout#3]
![error](https://user-images.githubusercontent.com/21986591/33053585-50ac8746-ceaf-11e7-8630-8c641189ec98.gif)

**Comment by krayc425** [comment]
@fandongtongxue bug 已知晓，已加入 TODO List，感谢反馈

**Comment by fandongtongxue** [comment]
游戏很不错,很上瘾

**Comment by krayc425** [comment]
@ @fandongtongxue 哈哈感谢，争取把这些问题尽快解决掉

**Comment by fandongtongxue** [comment]
@songkuixi 其实刚才那个不是一直水平,只是等待时间较长,下面这个真是死循环了
![error](http://oz0y4mei6.bkt.clouddn.com/error.gif)

**Comment by krayc425** [comment]
@fandongtongxue 嗯我会给他一个最小角度的 不过下面这种情况我已经做了预防怎么还会出现QAQ

**Comment by ZoharWang** [comment]
卡在左下角不动了|ω・）

![](https://i.imgur.com/UlVAuMc.gif)

**Comment by krayc425** [comment]
@ZoharWang 我感受到了这种绝望 不过是为什么呢……我暂时把它归于 SpriteKit 的锅哈哈哈 不过后面我会给他一个最低速度的所以应该不会停下
